apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ .Values.labels2.app | quote }}
    owner: {{ .Values.labels2.owner | quote }}
    environment: {{ .Values.labels2.environment | quote }}
  name: {{ .Values.labels2.deployLabel }}
  namespace: {{ .Release.Namespace }}
rules:
  # Allow Dashboard to create 'kubernetes-dashboard-key-holder' secret.
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create

  # Allow Dashboard to create 'kubernetes-dashboard-settings' config map.
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - create

