apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.labels.app | quote }}
    owner: {{ .Values.labels.owner | quote }}
    environment: {{ .Values.labels.environment | quote }}
  name: {{ .Values.deployName }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.deployLabel }}
  type: {{ .Values.service.type }}
